### ISSUE TITLE
W7 typo in main.cpp - submission impossible

### ISSUE THREAD

**Issue by mazimia** [Seneca-244200/OOP-Workshops#4]
In main.cpp and main_prof.cpp on line 87:41

moveAndLoad() argument is 3456

When added to previous cargo on line 85:48 (i.e. 2345) the resulting value is 5801. 
However the truck capacity is 5432 per line 82:38. 

The correct_output.txt/submitter program/tester expects that this cargo is added to the truck (correct_output.txt line 31), but it will always exceed capacity. 

The correct argument should be 3087. 

Lab is impossible to submit.

**Comment by joulecpa** [comment]
This isn't an issue though the wording may be a bit unclear in the specs. The intention of the load cargo function is to load without exceeding capacity in that it means to load as much as possible without exceeding capacity. Ie if we have a cap of 500 and we're currently at 400 load, an attempt to load 200 more will have it so the load becomes 500 and caps out (100 is loaded on and the other 100 is discarded).
