### ISSUE TITLE
W2P1 DMA Image isn't available

### ISSUE THREAD

**Issue by aruzaev** [Seneca-244200/OOP-Workshops#8]
In "The Code" section of the LAB section of the readme, the hyperlink for the DMA image goes to an error 404

![Screenshot 2022-05-24 173144](https://user-images.githubusercontent.com/48188754/170136029-532607a3-6e41-4944-837f-237f8f0a6cba.png)
.

**Comment by joulecpa** [comment]
Resolved missing image directory
