### ISSUE TITLE
WS03 main.cpp data does not reflect correct_output.txt on matrix

### ISSUE THREAD

**Issue by marcusgeorgievski** [Seneca-244200/OOP-Workshops#8]
correct_output.txt on matrix does not include the `{"Oculus", 7441.22}` project in its output. It would need to be removed from main.cpp or the submitter needs to updated if we are to not modify main.cpp.

**Comment by lctoye** [comment]
> correct_output.txt on matrix does not include the `{"Oculus", 7441.22}` project in its output. It would need to be removed from main.cpp or the submitter needs to updated if we are to not modify main.cpp.

The workshop states that new projects should only be added to the array if the new project cost does not exceed the remaining budget. If you add that condition to your addProjects(); function, you should be able to get the required output without modifying main.cpp.

**Comment by marcusgeorgievski** [comment]
> 

Yep, missed that
